language: python
python:
  - 2.7
  - 3.3
  - 3.5
install:
  - pip install pytest==3.0.6
  - pip install pytest-cov pybuilder coveralls pytest-mock mock responses
script:
  pyb
after_success:
  coveralls
